[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "RPi.GPIO.*"
ignore_missing_imports = true

[tool.ruff.lint]
select = ["F", "E", "W", "I", "N", "UP", "ANN", "B", "A"]
ignore = []